# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('group_channel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('number', models.IntegerField()),
                ('phase', models.CharField(max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameTrick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('number', models.IntegerField()),
                ('discards', models.CharField(max_length=12)),
                ('seat_order', models.CharField(max_length=12)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.GameRound')),
            ],
        ),
        migrations.CreateModel(
            name='MatchMakingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=24)),
                ('seat', models.IntegerField()),
                ('hand', models.CharField(max_length=39)),
                ('points', models.IntegerField()),
                ('active_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_app.Game')),
                ('active_queue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_app.MatchMakingQueue')),
            ],
        ),
    ]
