# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 03:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import game_app.models.list_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('group_channel', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=-1)),
                ('phase', models.CharField(default='', max_length=10)),
                ('hearts_broken', models.BooleanField(default=False)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='MatchMakingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=12)),
                ('total_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PassRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('direction', models.IntegerField(default=0)),
                ('passed_cards', game_app.models.list_fields.CardListField(default=[], max_length=39)),
                ('seats_received', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=4)),
                ('game_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_app.GameRound')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disconnected', models.BooleanField(default=False)),
                ('channel', models.CharField(default='', max_length=27)),
                ('position', models.IntegerField(default=None, null=True)),
                ('hand', game_app.models.list_fields.CardListField(default=[], max_length=39)),
                ('game_points', models.IntegerField(default=0)),
                ('hand_points', models.IntegerField(default=0)),
                ('new_elo', models.IntegerField(default=0)),
                ('new_rank', models.IntegerField(default=0)),
                ('new_rank_progress', models.IntegerField(default=0)),
                ('place_this_game', models.IntegerField(default=0)),
                ('enrolled_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_app.Game')),
                ('enrolled_queue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_app.MatchMakingQueue')),
            ],
        ),
        migrations.CreateModel(
            name='TrickTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=None, null=True)),
                ('first_seat', models.IntegerField(default=None, null=True)),
                ('discards', game_app.models.list_fields.CardListField(default=[], max_length=39)),
                ('expected_seat', models.IntegerField(default=None, null=True)),
                ('hearts_broken', models.BooleanField(default=False)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.GameRound')),
            ],
        ),
    ]
