# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakingqueue',
            name='name',
            field=models.CharField(default='default', max_length=12),
        ),
    ]
