# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_matchmakingqueue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='channel',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=models.CharField(default='', max_length=39),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='seat',
            field=models.IntegerField(default=-1),
        ),
    ]
