# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_auto_20170319_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePassPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('direction', models.IntegerField(default=0)),
                ('passed_cards', models.CharField(default='', max_length=36)),
            ],
        ),
        migrations.AddField(
            model_name='gameround',
            name='hearts_broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='group_channel',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_app.Game'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='phase',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='gametrick',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gametrick',
            name='discards',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='gametrick',
            name='number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='gametrick',
            name='seat_order',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='gamepassphase',
            name='game_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.GameRound'),
        ),
    ]
