# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import game_app.models.list_fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_auto_20170320_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('direction', models.IntegerField(default=0)),
                ('passed_cards', game_app.models.list_fields.CardListField(default=[], max_length=65)),
                ('seats_received', game_app.models.list_fields.SmallIntListField(default=[], max_length=16)),
                ('game_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_app.GameRound')),
            ],
        ),
        migrations.RemoveField(
            model_name='gamepassphase',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='gametrick',
            name='game_round',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='active_game',
            new_name='enrolled_game',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='active_queue',
            new_name='enrolled_queue',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='points',
            new_name='game_points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='seat',
        ),
        migrations.AddField(
            model_name='player',
            name='disconnected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='hand_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=game_app.models.list_fields.CardListField(default=[], max_length=65),
        ),
        migrations.DeleteModel(
            name='GamePassPhase',
        ),
        migrations.DeleteModel(
            name='GameTrick',
        ),
    ]
