# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
