# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 22:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_account_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 7, 22, 55, 30, 103960)),
        ),
    ]
