# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import game_app.models.list_fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_auto_20170326_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrickTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=None, null=True)),
                ('first_seat', models.IntegerField(default=None, null=True)),
                ('discards', game_app.models.list_fields.CardListField(default=[], max_length=65)),
                ('expected_seat', models.IntegerField(default=None, null=True)),
                ('hearts_broken', models.BooleanField(default=False)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.GameRound')),
            ],
        ),
    ]
