# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0006_trickturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='new_elo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='new_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='new_rank_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='place_this_game',
            field=models.IntegerField(default=0),
        ),
    ]
