# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0008_auto_20170407_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
