# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0009_auto_20170410_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bank_ms',
            field=models.IntegerField(default=10000),
        ),
    ]
