# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0011_auto_20170427_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='rank_promote',
        ),
    ]
