# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0012_remove_account_rank_promote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='rank_points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='new_rank',
        ),
        migrations.RemoveField(
            model_name='player',
            name='new_rank_progress',
        ),
        migrations.AlterField(
            model_name='account',
            name='rank',
            field=models.CharField(default='', max_length=13),
        ),
    ]
